### ISSUE TITLE
pip package?

### ISSUE THREAD

**Issue by pattyland** [Hereath/avea#1]
Hi there, this looks awesome!
Would min publishing that as a [pip package](https://pypi.org/)?
Greets,
Sören

**Comment by Hereath** [comment]
Hi ! Thanks !
I've never published a package to pip but I will look into it, this might be a better way of installing / using it. 
I will update the issue accordingly !

**Comment by pattyland** [comment]
That would be awesome! I want to publish an avea component for home assistant: https://www.home-assistant.io/components/

As you library is already python based, if would be the perfect base. But the requirement for the use of libraries in home assistant is that the library is hosted of PyPI.

**Comment by Hereath** [comment]
Check it out : [avea on pip !](https://pypi.org/project/avea/) 🎉 

This is juste the bare code uploaded to pip, so it's not perfect for library use. Some changes might be needed in this regard (I'll look into it), as well as making a compatible documentation for python's own help menu.

If you have any improvements or suggestions, they are all welcome 😄 
I will leave the issue open, until it becomes more library-like.

**Comment by Hereath** [comment]
hey @pattyland, I've refactor the code to be more lib-friendly, and now everything should work as expected ! I'll close the issue as the lib is now functional.
